[project]
name = "cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
dependencies = [
    "format",
    "rich>=13.9.4",
    "typer>=0.15.2",
]

[project.scripts]
main = "cli:app"

[tool.uv.sources]
format = { workspace = true }

[dependency-groups]
dev = []
